CryptoTracker/Controllers/DealController.cs
using CryptoTracker.DAL.Interfaces;
using CryptoTracker.Domain.Entity;
using CryptoTracker.Domain.Response;
using CryptoTracker.Domain.Enum;
using CryptoTracker.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using CryptoTracker.Domain.ViewModels.Deal;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CryptoTracker.Controllers
{
    public class DealController : Controller
    {
        private readonly IDealService _dealService;
        private readonly IUtilityService _utilityService;

        public DealController(IDealService dealService, IUtilityService utilityService)
        {
            _dealService = dealService;
            _utilityService = utilityService;
        }

        [HttpGet]
        public async Task<IActionResult> GetDeals(string name)
        {
            ViewBag.Currencies = new SelectList(_utilityService.GetCurrencies().Data, "Key", "Value");
            ViewBag.DealTypes = new SelectList(_utilityService.GetDealTypes().Data, "Key", "Value");
            var response = await _dealService.GetDealsByUserName(name);
            if (response.StatusCode == Domain.Enum.StatusCode.OK || response.StatusCode == Domain.Enum.StatusCode.ObjectNotFound)
            {
                return View(response.Data);
            }
        
            return RedirectToAction("Error", "Home");
        }
    }
}

CryptoTracker/Views/Deal/GetDeals.cshtml
@using CryptoTracker.Domain.Enum
@using CryptoTracker.Domain.Utility
@using CryptoTracker.Domain.Entity
@model IEnumerable<CryptoTracker.Domain.Entity.Deal>

@{
    ViewBag.Title = "title";
}
<div class="d-flex flex-column align-items-center justify-content-center">
    <script type="text/babel" src="~/js/deal.jsx"></script>
    <div class="accordion w-50">
        @{
            if (Model == null)
            {
                <h2>Add deal first</h2>
            }
        }
        <div id="app"></div>
    </div>
</div>
<a class="btn-add" data-toggle="modal" href="#modal-1" onclick="setId()"><img src="~/icons/plus-thick.png"/></a>

CryptoTracker/Views/Deal/SaveDeal.cshtml
@model CryptoTracker.Domain.Entity.Deal

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="d-flex align-content-center justify-content-center">
    <form asp-controller="Deal" asp-action="SaveDeal" enctype="multipart/form-data">
        @{
            if (Model == null)
            {
                <input asp-for="Id" hidden value="0"/>
            }
            else
            {
                <input asp-for="Id" hidden value="@Model.Id"/>
            }
        }
        <div asp-validation-summary="All"></div>
        <div class="col">
            <div class="form-group col-md-4">
                <label asp-for="Currency" class="col-form-label"></label>
                @Html.DropDownList("Currency", ViewBag.Currencies as SelectList)
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Amount" class="col-form-label"></label>
                <input asp-for="Amount" type="number" step="any" required/>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Rate" class="col-form-label">Rate (USD for 1 cryptocoin)</label>
                <input asp-for="Rate" type="number" step="0.01" required/>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="DealType" class="col-form-label"></label>
                @Html.DropDownList("DealType", ViewBag.DealTypes as SelectList)
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Commentary" class="col-form-label">Commentary</label>
                <textarea asp-for="Commentary" type="text"></textarea>
            </div>
        </div>
        <input type="submit" class="btn-success">
    </form>
</div>

CryptoTracker/Views/Deal/SaveDealModal.cshtml
@model CryptoTracker.Domain.Entity.Deal

@* <link rel="stylesheet" type="text/css" href="~/css/custom.css"/> *@
<div class="d-flex align-content-center justify-content-center">
    <form asp-controller="Deal" asp-action="SaveDeal" enctype="multipart/form-data">
        @{
            if (Model == null)
            {
                <input asp-for="Id" hidden value="0"/>
            }
            else
            {
                <input asp-for="Id" hidden value="@Model.Id"/>
            }
        }
        <div asp-validation-summary="All"></div>
        <div class="col modal-custom d-flex flex-column align-items-center">
            <div class="form-group col-md-8">
                <label asp-for="Currency" class="col-form-label"></label>
                @Html.DropDownList("Currency", ViewBag.Currencies as SelectList)
            </div>
            <div class="form-group col-md-8">
                <label asp-for="Amount" class="col-form-label"></label>
                <input asp-for="Amount" type="number" step="any" required/>
            </div>
            <div class="form-group col-md-8">
                <label asp-for="Rate" class="col-form-label">Rate (USD for 1 cryptocoin)</label>
                <input asp-for="Rate" type="number" step="0.01" required/>
            </div>
            <div class="form-group col-md-8">
                <label asp-for="DealType" class="col-form-label"></label>
                @Html.DropDownList("DealType", ViewBag.DealTypes as SelectList)
            </div>
            <div class="form-group col-md-8">
                <label asp-for="Commentary" class="col-form-label">Commentary</label>
                <textarea asp-for="Commentary" type="text"></textarea>
            </div>
        </div>
        <div class="d-flex flex-row justify-content-around">
            @{
                if (Model.Id == 0)
                {
                    <input class="modal-save" type="image" src="~/icons/check.png" alt="submit">
                }
                else
                {
                    <input class="modal-save" type="image" src="~/icons/check.png" alt="submit">
                }
            }
        </div>
    </form>
</div>